version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: btc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: btc_db
      POSTGRES_USER: btc_user
      POSTGRES_PASSWORD: btc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
